const loginStyle = {
    page: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        height: "100vh",
        backgroundColor: "#f5f5f5",
    },
    mainTitle: {
        fontSize: "50px",
        fontWeight: "bold",
        color: "#333333",
        marginBottom: "20px",
        textAlign: "center",
    },
    container: {
        backgroundColor: "#ffffff",
        boxShadow: "0 4px 8px rgba(0, 0, 0, 0.2)",
        borderRadius: "10px",
        width: "400px",
        padding: "30px",
        textAlign: "center",
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
    },
    title: {
        fontSize: "24px",
        color: "#555555",
        marginBottom: "20px",
    },
    inputContainer: {
        width: "100%",
        display: "flex",
        flexDirection: "column",
        gap: "15px",
        paddingBottom: "20px",
    },
    error: {
        color: "#ff4d4f",
        fontSize: "14px",
        marginTop: "5px",
    },
    inputBox: {
        width: "100%",
        padding: "10px",
        fontSize: "16px",
        border: "1px solid #cccccc",
        borderRadius: "5px",
        boxSizing: "border-box",
        transition: "border-color 0.3s",
    },
    inputButton: {
        width: "100%",
        padding: "12px",
        fontSize: "16px",
        color: "#ffffff",
        backgroundColor: "purple",
        border: "none",
        borderRadius: "5px",
        cursor: "pointer",
        transition: "background-color 0.3s",
    },
};

export default loginStyle;
